#ifndef __validator_keyframes__
#define __validator_keyframes__

/**
@file
Subclass of rcdlgKeyframes, which is generated by wxFormBuilder.
*/

#include "resources/res_keyframe.h"

#include <vector>
#include <wx/stc/stc.h>

/** Implementing rcdlgKeyframes */
class dlgKeyframes : public rcdlgKeyframes {
private:
    enum {
        Method_SimpleLinear = 0,
        Method_SimpleAcceleration = 1,
        Method_SimpleJerk = 2,
        Method_AccelDeccel = 3,
        Method_SineBob = 4,
        Method_Dampened = 5,
        Method_MAX
    };

    enum {
        Method_R_SimpleLinear = 0,
        Method_R_SimpleAcceleration = 1,
        Method_R_MAX
    };

    std::vector<float> m_times;
    std::vector<float> m_axes[3];
    unsigned long m_frames;
    float m_startTime;
    float m_endTime;

    bool m_init;

    wxChoice* m_choiceMethod[3];
    wxTextCtrl* m_textSVal[3];
    wxTextCtrl* m_textSVel[3];
    wxTextCtrl* m_textPer[3];
    wxTextCtrl* m_textPerOff[3];
    wxTextCtrl* m_textVal[3];
    wxTextCtrl* m_textEVel[3];
    wxTextCtrl* m_textEVal[3];

    wxStyledTextCtrl* m_stc;

    void DoTypeChange();
    void DoGridChange();
    void DoCalculation(int axis);
    void DoCalculationT(int axis);
    void DoCalculationR(int axis);
    void Init();

    static wxString GetMethodString(int type, int method);
protected:
	// Handlers for rcdlgKeyframes events.
	void OnInsert( wxCommandEvent& event );
	void OnInsertClose( wxCommandEvent& event );
	void OnClose( wxCommandEvent& event );
    virtual void OnTypeChange( wxCommandEvent& event );
    virtual void OnMethodChange( wxCommandEvent& event );
    virtual void OnValueXChange( wxCommandEvent& event );
    virtual void OnValueYChange( wxCommandEvent& event );
    virtual void OnValueZChange( wxCommandEvent& event );
    virtual void OnGridChange( wxCommandEvent& event );

public:
	/** Constructor */
	dlgKeyframes( wxWindow* parent, wxStyledTextCtrl* stc );
};

#endif // __validator_keyframes__
