
#include "ManagerOVL.h"
#include "ManagerBAN.h"
#include "ManagerBSH.h"
#include "ManagerCED.h"
#include "ManagerCHG.h"
#include "ManagerCID.h"
//#include "ManagerFLIC.h"  // Not meant for direct access
#include "ManagerFTX.h"
#include "ManagerGSI.h"
#include "ManagerSAT.h"
#include "ManagerSHS.h"
#include "ManagerSPL.h"
#include "ManagerSID.h"
#include "ManagerSTA.h"
#include "ManagerSVD.h"
#include "ManagerTEX.h"
#include "ManagerTXT.h"
#include "ManagerWAI.h"

