//
// This file was automatically generated by wxrc, do not edit by hand.
//

#ifndef __xrc_attract_h__
#define __xrc_attract_h__
class dlgAttract : public wxDialog {
protected:
 wxStaticText* m_staticText1;
 wxStaticText* m_staticText9;
 wxTextCtrl* m_Name;
 wxChoice* m_Type;
 wxStaticText* m_staticText10;
 wxStaticText* m_staticText11;
 wxChoice* m_NameString;
 wxChoice* m_Description;
 wxStaticText* m_staticText13;
 wxStaticText* m_staticText132;
 wxTextCtrl* m_Unk2;
 wxTextCtrl* m_Unk3;
 wxStaticText* m_staticText25;
 wxChoice* m_SceneryItem;
 wxButton* m_OK;
 wxButton* m_Cancel;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,_T("dlgAttract"), _T("wxDialog"));
  m_staticText1 = XRCCTRL(*this,"m_staticText1",wxStaticText);
  m_staticText9 = XRCCTRL(*this,"m_staticText9",wxStaticText);
  m_Name = XRCCTRL(*this,"m_Name",wxTextCtrl);
  m_Type = XRCCTRL(*this,"m_Type",wxChoice);
  m_staticText10 = XRCCTRL(*this,"m_staticText10",wxStaticText);
  m_staticText11 = XRCCTRL(*this,"m_staticText11",wxStaticText);
  m_NameString = XRCCTRL(*this,"m_NameString",wxChoice);
  m_Description = XRCCTRL(*this,"m_Description",wxChoice);
  m_staticText13 = XRCCTRL(*this,"m_staticText13",wxStaticText);
  m_staticText132 = XRCCTRL(*this,"m_staticText132",wxStaticText);
  m_Unk2 = XRCCTRL(*this,"m_Unk2",wxTextCtrl);
  m_Unk3 = XRCCTRL(*this,"m_Unk3",wxTextCtrl);
  m_staticText25 = XRCCTRL(*this,"m_staticText25",wxStaticText);
  m_SceneryItem = XRCCTRL(*this,"m_SceneryItem",wxChoice);
  m_OK = XRCCTRL(*this,"m_OK",wxButton);
  m_Cancel = XRCCTRL(*this,"m_Cancel",wxButton);
 }
public:
dlgAttract(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};

void 
InitXmlAttract();
#endif
