//
// This file was automatically generated by wxrc, do not edit by hand.
//

#ifndef __xrc_effectmenu_h__
#define __xrc_effectmenu_h__
class menu_effect : public wxMenu {
protected:
 wxMenu* menu_effect_light;
 wxMenu* menu_effect_particle;
 wxMenu* menu_effect_launcher;
 wxMenu* menu_effect_peep;
 wxMenu* menu_effect_fountain;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,_T("menu_effect"), _T("wxMenu"));
  menu_effect_light = XRCCTRL(*this,"menu_effect_light",wxMenu);
  menu_effect_particle = XRCCTRL(*this,"menu_effect_particle",wxMenu);
  menu_effect_launcher = XRCCTRL(*this,"menu_effect_launcher",wxMenu);
  menu_effect_peep = XRCCTRL(*this,"menu_effect_peep",wxMenu);
  menu_effect_fountain = XRCCTRL(*this,"menu_effect_fountain",wxMenu);
 }
public:
menu_effect(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};

void 
InitXmlEffectMenu();
#endif
