//
// This file was automatically generated by wxrc, do not edit by hand.
//

#ifndef __xrc_stall_h__
#define __xrc_stall_h__
class dlgStall : public wxDialog {
protected:
 wxStaticText* m_staticText1;
 wxStaticText* m_staticText9;
 wxTextCtrl* m_Name;
 wxChoice* m_Type;
 wxStaticText* m_staticText10;
 wxStaticText* m_staticText11;
 wxChoice* m_NameString;
 wxChoice* m_Description;
 wxStaticText* m_staticText13;
 wxStaticText* m_staticText132;
 wxTextCtrl* m_Unk2;
 wxTextCtrl* m_Unk3;
 wxStaticText* m_staticText25;
 wxChoice* m_SceneryItem;
 wxStaticText* m_staticText26;
 wxStaticText* m_staticText27;
 wxTextCtrl* m_Unk11;
 wxTextCtrl* m_Unk12;
 wxStaticText* m_staticText28;
 wxStaticText* m_staticText32;
 wxTextCtrl* m_Unk13;
 wxTextCtrl* m_Unk14;
 wxStaticText* m_staticText33;
 wxStaticText* m_staticText34;
 wxTextCtrl* m_Unk15;
 wxTextCtrl* m_Unk16;
 wxButton* m_OK;
 wxButton* m_Cancel;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,_T("dlgStall"), _T("wxDialog"));
  m_staticText1 = XRCCTRL(*this,"m_staticText1",wxStaticText);
  m_staticText9 = XRCCTRL(*this,"m_staticText9",wxStaticText);
  m_Name = XRCCTRL(*this,"m_Name",wxTextCtrl);
  m_Type = XRCCTRL(*this,"m_Type",wxChoice);
  m_staticText10 = XRCCTRL(*this,"m_staticText10",wxStaticText);
  m_staticText11 = XRCCTRL(*this,"m_staticText11",wxStaticText);
  m_NameString = XRCCTRL(*this,"m_NameString",wxChoice);
  m_Description = XRCCTRL(*this,"m_Description",wxChoice);
  m_staticText13 = XRCCTRL(*this,"m_staticText13",wxStaticText);
  m_staticText132 = XRCCTRL(*this,"m_staticText132",wxStaticText);
  m_Unk2 = XRCCTRL(*this,"m_Unk2",wxTextCtrl);
  m_Unk3 = XRCCTRL(*this,"m_Unk3",wxTextCtrl);
  m_staticText25 = XRCCTRL(*this,"m_staticText25",wxStaticText);
  m_SceneryItem = XRCCTRL(*this,"m_SceneryItem",wxChoice);
  m_staticText26 = XRCCTRL(*this,"m_staticText26",wxStaticText);
  m_staticText27 = XRCCTRL(*this,"m_staticText27",wxStaticText);
  m_Unk11 = XRCCTRL(*this,"m_Unk11",wxTextCtrl);
  m_Unk12 = XRCCTRL(*this,"m_Unk12",wxTextCtrl);
  m_staticText28 = XRCCTRL(*this,"m_staticText28",wxStaticText);
  m_staticText32 = XRCCTRL(*this,"m_staticText32",wxStaticText);
  m_Unk13 = XRCCTRL(*this,"m_Unk13",wxTextCtrl);
  m_Unk14 = XRCCTRL(*this,"m_Unk14",wxTextCtrl);
  m_staticText33 = XRCCTRL(*this,"m_staticText33",wxStaticText);
  m_staticText34 = XRCCTRL(*this,"m_staticText34",wxStaticText);
  m_Unk15 = XRCCTRL(*this,"m_Unk15",wxTextCtrl);
  m_Unk16 = XRCCTRL(*this,"m_Unk16",wxTextCtrl);
  m_OK = XRCCTRL(*this,"m_OK",wxButton);
  m_Cancel = XRCCTRL(*this,"m_Cancel",wxButton);
 }
public:
dlgStall(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};

void 
InitXmlStall();
#endif
