//
// This file was automatically generated by wxrc, do not edit by hand.
//

#ifndef __xrc_mesh_h__
#define __xrc_mesh_h__
class dlgMesh : public wxDialog {
protected:
 wxCheckBox* m_checkDontImport;
 wxStaticText* m_staticText5;
 wxComboBox* m_cbTextureName;
 wxStaticText* m_staticText6;
 wxChoice* m_choiceTextureStyle;
 wxStaticText* m_staticText7;
 wxChoice* m_choiceShowTexture;
 wxStaticText* m_staticText8;
 wxChoice* m_choiceTextureFlags;
 wxStaticText* m_staticText9;
 wxChoice* m_choiceUnknown;
 wxCheckBox* m_checkApplyAll;
 wxButton* m_btLoad;
 wxButton* m_btOk;
 wxButton* m_btCancel;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,_T("dlgMesh"), _T("wxDialog"));
  m_checkDontImport = XRCCTRL(*this,"m_checkDontImport",wxCheckBox);
  m_staticText5 = XRCCTRL(*this,"m_staticText5",wxStaticText);
  m_cbTextureName = XRCCTRL(*this,"m_cbTextureName",wxComboBox);
  m_staticText6 = XRCCTRL(*this,"m_staticText6",wxStaticText);
  m_choiceTextureStyle = XRCCTRL(*this,"m_choiceTextureStyle",wxChoice);
  m_staticText7 = XRCCTRL(*this,"m_staticText7",wxStaticText);
  m_choiceShowTexture = XRCCTRL(*this,"m_choiceShowTexture",wxChoice);
  m_staticText8 = XRCCTRL(*this,"m_staticText8",wxStaticText);
  m_choiceTextureFlags = XRCCTRL(*this,"m_choiceTextureFlags",wxChoice);
  m_staticText9 = XRCCTRL(*this,"m_staticText9",wxStaticText);
  m_choiceUnknown = XRCCTRL(*this,"m_choiceUnknown",wxChoice);
  m_checkApplyAll = XRCCTRL(*this,"m_checkApplyAll",wxCheckBox);
  m_btLoad = XRCCTRL(*this,"m_btLoad",wxButton);
  m_btOk = XRCCTRL(*this,"m_btOk",wxButton);
  m_btCancel = XRCCTRL(*this,"m_btCancel",wxButton);
 }
public:
dlgMesh(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};

void 
InitXmlMesh();
#endif
