//
// This file was automatically generated by wxrc, do not edit by hand.
//

#ifndef __xrc_stallman_h__
#define __xrc_stallman_h__
class dlgStallMan : public wxDialog {
protected:
 wxListBox* m_StallList;
 wxButton* m_Add;
 wxButton* m_Edit;
 wxButton* m_Delete;
 wxButton* m_Close;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,_T("dlgStallMan"), _T("wxDialog"));
  m_StallList = XRCCTRL(*this,"m_StallList",wxListBox);
  m_Add = XRCCTRL(*this,"m_Add",wxButton);
  m_Edit = XRCCTRL(*this,"m_Edit",wxButton);
  m_Delete = XRCCTRL(*this,"m_Delete",wxButton);
  m_Close = XRCCTRL(*this,"m_Close",wxButton);
 }
public:
dlgStallMan(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};

void 
InitXmlStallMan();
#endif
