//
// This file was automatically generated by wxrc, do not edit by hand.
//

#ifndef __xrc_info_h__
#define __xrc_info_h__
class dlgInfo : public wxDialog {
protected:
 wxTextCtrl* m_textInfo;
 wxButton* m_btOk;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,_T("dlgInfo"), _T("wxDialog"));
  m_textInfo = XRCCTRL(*this,"m_textInfo",wxTextCtrl);
  m_btOk = XRCCTRL(*this,"m_btOk",wxButton);
 }
public:
dlgInfo(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};

void 
InitXmlInfo();
#endif
