//
// This file was automatically generated by wxrc, do not edit by hand.
//

#ifndef __xrc_createscenery_h__
#define __xrc_createscenery_h__
class dlgCreateScenery : public wxDialog {
protected:
 wxStaticLine* m_staticline1;
 wxSpinButton* m_spinTexture;
 wxButton* m_btTextureAdd;
 wxButton* m_btTextureEdit;
 wxButton* m_btTextureCopy;
 wxButton* m_btTextureDel;
 wxButton* m_btTextureClear;
 wxSpinButton* m_spinModel;
 wxButton* m_btModelAdd;
 wxButton* m_btModelEdit;
 wxButton* m_btModelCopy;
 wxButton* m_btModelDel;
 wxButton* m_btModelClear;
 wxButton* m_btLODAdd;
 wxButton* m_btLODEdit;
 wxButton* m_btLODCopy;
 wxButton* m_btLODDel;
 wxButton* m_btLODAuto;
 wxButton* m_btLODClear;
 wxButton* m_btCreate;
 wxStaticText* m_staticText19;
 wxChoice* m_choiceExpansion;
 wxCheckBox* m_checkGreenery;
 wxStaticText* m_staticText20;
 wxTextCtrl* m_textSway;
 wxCheckBox* m_checkShadow;
 wxStaticText* m_staticText21;
 wxTextCtrl* m_textBrightness;
 wxCheckBox* m_checkRotation;
 wxStaticText* m_staticText22;
 wxTextCtrl* m_textScale;
 wxButton* m_btVisualNormal;
 wxButton* m_btVisualSwayingTree;
 wxCheckBox* m_checkShowUnknown;
 wxPanel* m_panelUnknown;
 wxStaticText* m_staticText23;
 wxCheckBox* m_checkUnknown;
 wxStaticText* m_staticText24;
 wxTextCtrl* m_textUnknownFactor;
 wxStaticText* m_staticText25;
 wxTextCtrl* m_textUnknown6;
 wxStaticText* m_staticText26;
 wxTextCtrl* m_textUnknown7;
 wxStaticText* m_staticText27;
 wxTextCtrl* m_textUnknown8;
 wxStaticText* m_staticText28;
 wxTextCtrl* m_textUnknown9;
 wxStaticText* m_staticText29;
 wxTextCtrl* m_textUnknown10;
 wxStaticText* m_staticText30;
 wxTextCtrl* m_textUnknown11;
 wxTextCtrl* m_textReference;
 wxButton* m_btReferenceAdd;
 wxButton* m_btReferenceDel;
 wxButton* m_btReferenceClear;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,_T("dlgCreateScenery"), _T("wxDialog"));
  m_staticline1 = XRCCTRL(*this,"m_staticline1",wxStaticLine);
  m_spinTexture = XRCCTRL(*this,"m_spinTexture",wxSpinButton);
  m_btTextureAdd = XRCCTRL(*this,"m_btTextureAdd",wxButton);
  m_btTextureEdit = XRCCTRL(*this,"m_btTextureEdit",wxButton);
  m_btTextureCopy = XRCCTRL(*this,"m_btTextureCopy",wxButton);
  m_btTextureDel = XRCCTRL(*this,"m_btTextureDel",wxButton);
  m_btTextureClear = XRCCTRL(*this,"m_btTextureClear",wxButton);
  m_spinModel = XRCCTRL(*this,"m_spinModel",wxSpinButton);
  m_btModelAdd = XRCCTRL(*this,"m_btModelAdd",wxButton);
  m_btModelEdit = XRCCTRL(*this,"m_btModelEdit",wxButton);
  m_btModelCopy = XRCCTRL(*this,"m_btModelCopy",wxButton);
  m_btModelDel = XRCCTRL(*this,"m_btModelDel",wxButton);
  m_btModelClear = XRCCTRL(*this,"m_btModelClear",wxButton);
  m_btLODAdd = XRCCTRL(*this,"m_btLODAdd",wxButton);
  m_btLODEdit = XRCCTRL(*this,"m_btLODEdit",wxButton);
  m_btLODCopy = XRCCTRL(*this,"m_btLODCopy",wxButton);
  m_btLODDel = XRCCTRL(*this,"m_btLODDel",wxButton);
  m_btLODAuto = XRCCTRL(*this,"m_btLODAuto",wxButton);
  m_btLODClear = XRCCTRL(*this,"m_btLODClear",wxButton);
  m_btCreate = XRCCTRL(*this,"m_btCreate",wxButton);
  m_staticText19 = XRCCTRL(*this,"m_staticText19",wxStaticText);
  m_choiceExpansion = XRCCTRL(*this,"m_choiceExpansion",wxChoice);
  m_checkGreenery = XRCCTRL(*this,"m_checkGreenery",wxCheckBox);
  m_staticText20 = XRCCTRL(*this,"m_staticText20",wxStaticText);
  m_textSway = XRCCTRL(*this,"m_textSway",wxTextCtrl);
  m_checkShadow = XRCCTRL(*this,"m_checkShadow",wxCheckBox);
  m_staticText21 = XRCCTRL(*this,"m_staticText21",wxStaticText);
  m_textBrightness = XRCCTRL(*this,"m_textBrightness",wxTextCtrl);
  m_checkRotation = XRCCTRL(*this,"m_checkRotation",wxCheckBox);
  m_staticText22 = XRCCTRL(*this,"m_staticText22",wxStaticText);
  m_textScale = XRCCTRL(*this,"m_textScale",wxTextCtrl);
  m_btVisualNormal = XRCCTRL(*this,"m_btVisualNormal",wxButton);
  m_btVisualSwayingTree = XRCCTRL(*this,"m_btVisualSwayingTree",wxButton);
  m_checkShowUnknown = XRCCTRL(*this,"m_checkShowUnknown",wxCheckBox);
  m_panelUnknown = XRCCTRL(*this,"m_panelUnknown",wxPanel);
  m_staticText23 = XRCCTRL(*this,"m_staticText23",wxStaticText);
  m_checkUnknown = XRCCTRL(*this,"m_checkUnknown",wxCheckBox);
  m_staticText24 = XRCCTRL(*this,"m_staticText24",wxStaticText);
  m_textUnknownFactor = XRCCTRL(*this,"m_textUnknownFactor",wxTextCtrl);
  m_staticText25 = XRCCTRL(*this,"m_staticText25",wxStaticText);
  m_textUnknown6 = XRCCTRL(*this,"m_textUnknown6",wxTextCtrl);
  m_staticText26 = XRCCTRL(*this,"m_staticText26",wxStaticText);
  m_textUnknown7 = XRCCTRL(*this,"m_textUnknown7",wxTextCtrl);
  m_staticText27 = XRCCTRL(*this,"m_staticText27",wxStaticText);
  m_textUnknown8 = XRCCTRL(*this,"m_textUnknown8",wxTextCtrl);
  m_staticText28 = XRCCTRL(*this,"m_staticText28",wxStaticText);
  m_textUnknown9 = XRCCTRL(*this,"m_textUnknown9",wxTextCtrl);
  m_staticText29 = XRCCTRL(*this,"m_staticText29",wxStaticText);
  m_textUnknown10 = XRCCTRL(*this,"m_textUnknown10",wxTextCtrl);
  m_staticText30 = XRCCTRL(*this,"m_staticText30",wxStaticText);
  m_textUnknown11 = XRCCTRL(*this,"m_textUnknown11",wxTextCtrl);
  m_textReference = XRCCTRL(*this,"m_textReference",wxTextCtrl);
  m_btReferenceAdd = XRCCTRL(*this,"m_btReferenceAdd",wxButton);
  m_btReferenceDel = XRCCTRL(*this,"m_btReferenceDel",wxButton);
  m_btReferenceClear = XRCCTRL(*this,"m_btReferenceClear",wxButton);
 }
public:
dlgCreateScenery(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};

void 
InitXmlCreateScenery();
#endif
