//
// This file was automatically generated by wxrc, do not edit by hand.
//

#ifndef __xrc_lod_h__
#define __xrc_lod_h__
class dlgLOD : public wxDialog {
protected:
 wxStaticText* m_staticText6;
 wxChoice* m_choiceModel;
 wxStaticText* m_staticText8;
 wxTextCtrl* m_textDistance;
 wxButton* m_btDist40;
 wxButton* m_btDist100;
 wxButton* m_btDist4000;
 wxCheckBox* m_checkShowUnknown;
 wxPanel* m_panelUnknown;
 wxStaticText* m_staticText5;
 wxTextCtrl* m_textUnknown2;
 wxStaticText* m_staticText61;
 wxTextCtrl* m_textUnknown4;
 wxStaticText* m_staticText7;
 wxTextCtrl* m_textUnknown14;
 wxButton* m_btOk;
 wxButton* m_btCancel;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,_T("dlgLOD"), _T("wxDialog"));
  m_staticText6 = XRCCTRL(*this,"m_staticText6",wxStaticText);
  m_choiceModel = XRCCTRL(*this,"m_choiceModel",wxChoice);
  m_staticText8 = XRCCTRL(*this,"m_staticText8",wxStaticText);
  m_textDistance = XRCCTRL(*this,"m_textDistance",wxTextCtrl);
  m_btDist40 = XRCCTRL(*this,"m_btDist40",wxButton);
  m_btDist100 = XRCCTRL(*this,"m_btDist100",wxButton);
  m_btDist4000 = XRCCTRL(*this,"m_btDist4000",wxButton);
  m_checkShowUnknown = XRCCTRL(*this,"m_checkShowUnknown",wxCheckBox);
  m_panelUnknown = XRCCTRL(*this,"m_panelUnknown",wxPanel);
  m_staticText5 = XRCCTRL(*this,"m_staticText5",wxStaticText);
  m_textUnknown2 = XRCCTRL(*this,"m_textUnknown2",wxTextCtrl);
  m_staticText61 = XRCCTRL(*this,"m_staticText61",wxStaticText);
  m_textUnknown4 = XRCCTRL(*this,"m_textUnknown4",wxTextCtrl);
  m_staticText7 = XRCCTRL(*this,"m_staticText7",wxStaticText);
  m_textUnknown14 = XRCCTRL(*this,"m_textUnknown14",wxTextCtrl);
  m_btOk = XRCCTRL(*this,"m_btOk",wxButton);
  m_btCancel = XRCCTRL(*this,"m_btCancel",wxButton);
 }
public:
dlgLOD(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};

void 
InitXmlLOD();
#endif
