//
// This file was automatically generated by wxrc, do not edit by hand.
//

#ifndef __xrc_effect_h__
#define __xrc_effect_h__
class dlgEffect : public wxDialog {
protected:
 wxStaticText* m_11;
 wxStaticText* m_12;
 wxStaticText* m_13;
 wxStaticText* m_14;
 wxStaticText* m_21;
 wxStaticText* m_22;
 wxStaticText* m_23;
 wxStaticText* m_24;
 wxStaticText* m_31;
 wxStaticText* m_32;
 wxStaticText* m_33;
 wxStaticText* m_34;
 wxStaticText* m_41;
 wxStaticText* m_42;
 wxStaticText* m_43;
 wxStaticText* m_44;
 wxChoice* m_choicePoint;
 wxStaticText* m_staticText44;
 wxTextCtrl* m_textX;
 wxStaticText* m_staticText45;
 wxTextCtrl* m_textY;
 wxStaticText* m_staticText46;
 wxTextCtrl* m_textZ;
 wxButton* m_btPos;
 wxButton* m_btEdit;
 wxButton* m_btClear;
 wxStaticText* m_staticText47;
 wxTextCtrl* m_textEffectName;
 wxButton* m_btCreate;
 wxButton* m_btLoad;
 wxButton* m_btOk;
 wxButton* m_btCancel;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,_T("dlgEffect"), _T("wxDialog"));
  m_11 = XRCCTRL(*this,"m_11",wxStaticText);
  m_12 = XRCCTRL(*this,"m_12",wxStaticText);
  m_13 = XRCCTRL(*this,"m_13",wxStaticText);
  m_14 = XRCCTRL(*this,"m_14",wxStaticText);
  m_21 = XRCCTRL(*this,"m_21",wxStaticText);
  m_22 = XRCCTRL(*this,"m_22",wxStaticText);
  m_23 = XRCCTRL(*this,"m_23",wxStaticText);
  m_24 = XRCCTRL(*this,"m_24",wxStaticText);
  m_31 = XRCCTRL(*this,"m_31",wxStaticText);
  m_32 = XRCCTRL(*this,"m_32",wxStaticText);
  m_33 = XRCCTRL(*this,"m_33",wxStaticText);
  m_34 = XRCCTRL(*this,"m_34",wxStaticText);
  m_41 = XRCCTRL(*this,"m_41",wxStaticText);
  m_42 = XRCCTRL(*this,"m_42",wxStaticText);
  m_43 = XRCCTRL(*this,"m_43",wxStaticText);
  m_44 = XRCCTRL(*this,"m_44",wxStaticText);
  m_choicePoint = XRCCTRL(*this,"m_choicePoint",wxChoice);
  m_staticText44 = XRCCTRL(*this,"m_staticText44",wxStaticText);
  m_textX = XRCCTRL(*this,"m_textX",wxTextCtrl);
  m_staticText45 = XRCCTRL(*this,"m_staticText45",wxStaticText);
  m_textY = XRCCTRL(*this,"m_textY",wxTextCtrl);
  m_staticText46 = XRCCTRL(*this,"m_staticText46",wxStaticText);
  m_textZ = XRCCTRL(*this,"m_textZ",wxTextCtrl);
  m_btPos = XRCCTRL(*this,"m_btPos",wxButton);
  m_btEdit = XRCCTRL(*this,"m_btEdit",wxButton);
  m_btClear = XRCCTRL(*this,"m_btClear",wxButton);
  m_staticText47 = XRCCTRL(*this,"m_staticText47",wxStaticText);
  m_textEffectName = XRCCTRL(*this,"m_textEffectName",wxTextCtrl);
  m_btCreate = XRCCTRL(*this,"m_btCreate",wxButton);
  m_btLoad = XRCCTRL(*this,"m_btLoad",wxButton);
  m_btOk = XRCCTRL(*this,"m_btOk",wxButton);
  m_btCancel = XRCCTRL(*this,"m_btCancel",wxButton);
 }
public:
dlgEffect(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class dlgEffectLight : public wxDialog {
protected:
 wxStaticText* m_staticText30;
 wxChoice* m_choiceLightType;
 wxCheckBox* m_checkShines;
 wxCheckBox* m_checkBulb;
 wxStaticText* m_staticText31;
 wxChoice* m_choiceLightOption;
 wxStaticText* m_staticText32;
 wxStaticText* m_staticText33;
 wxTextCtrl* m_textLightRed;
 wxStaticText* m_staticText34;
 wxTextCtrl* m_textLightGreen;
 wxStaticText* m_staticText341;
 wxTextCtrl* m_textLightBlue;
 wxStaticText* m_staticText38;
 wxTextCtrl* m_textLightRadius;
 wxCheckBox* m_checkCM;
 wxTextCtrl* m_textPreview;
 wxButton* m_btOk;
 wxButton* m_btCancel;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,_T("dlgEffectLight"), _T("wxDialog"));
  m_staticText30 = XRCCTRL(*this,"m_staticText30",wxStaticText);
  m_choiceLightType = XRCCTRL(*this,"m_choiceLightType",wxChoice);
  m_checkShines = XRCCTRL(*this,"m_checkShines",wxCheckBox);
  m_checkBulb = XRCCTRL(*this,"m_checkBulb",wxCheckBox);
  m_staticText31 = XRCCTRL(*this,"m_staticText31",wxStaticText);
  m_choiceLightOption = XRCCTRL(*this,"m_choiceLightOption",wxChoice);
  m_staticText32 = XRCCTRL(*this,"m_staticText32",wxStaticText);
  m_staticText33 = XRCCTRL(*this,"m_staticText33",wxStaticText);
  m_textLightRed = XRCCTRL(*this,"m_textLightRed",wxTextCtrl);
  m_staticText34 = XRCCTRL(*this,"m_staticText34",wxStaticText);
  m_textLightGreen = XRCCTRL(*this,"m_textLightGreen",wxTextCtrl);
  m_staticText341 = XRCCTRL(*this,"m_staticText341",wxStaticText);
  m_textLightBlue = XRCCTRL(*this,"m_textLightBlue",wxTextCtrl);
  m_staticText38 = XRCCTRL(*this,"m_staticText38",wxStaticText);
  m_textLightRadius = XRCCTRL(*this,"m_textLightRadius",wxTextCtrl);
  m_checkCM = XRCCTRL(*this,"m_checkCM",wxCheckBox);
  m_textPreview = XRCCTRL(*this,"m_textPreview",wxTextCtrl);
  m_btOk = XRCCTRL(*this,"m_btOk",wxButton);
  m_btCancel = XRCCTRL(*this,"m_btCancel",wxButton);
 }
public:
dlgEffectLight(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};

void 
InitXmlEffect();
#endif
