//
// This file was automatically generated by wxrc, do not edit by hand.
//

#ifndef __xrc_model_h__
#define __xrc_model_h__
class dlgModel : public wxDialog {
protected:
 wxStaticText* m_staticText29;
 wxTextCtrl* m_textModelName;
 wxStaticText* m_staticText30;
 wxTextCtrl* m_textModelFile;
 wxButton* m_btModelOpen;
 wxButton* m_btMatrixEdit;
 wxButton* m_btMatrixSave;
 wxButton* m_btMatrixClear;
 wxStaticText* m_11;
 wxStaticText* m_12;
 wxStaticText* m_13;
 wxStaticText* m_14;
 wxStaticText* m_21;
 wxStaticText* m_22;
 wxStaticText* m_23;
 wxStaticText* m_24;
 wxStaticText* m_31;
 wxStaticText* m_32;
 wxStaticText* m_33;
 wxStaticText* m_34;
 wxStaticText* m_41;
 wxStaticText* m_42;
 wxStaticText* m_43;
 wxStaticText* m_44;
 wxButton* m_btEditMesh;
 wxSpinButton* m_spinEffect;
 wxButton* m_btEffectAdd;
 wxButton* m_btEffectEdit;
 wxButton* m_btEffectCopy;
 wxButton* m_btEffectDel;
 wxButton* m_btEffectAuto;
 wxButton* m_btEffectClear;
 wxButton* m_btLoad;
 wxButton* m_btOk;
 wxButton* m_btCancel;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,_T("dlgModel"), _T("wxDialog"));
  m_staticText29 = XRCCTRL(*this,"m_staticText29",wxStaticText);
  m_textModelName = XRCCTRL(*this,"m_textModelName",wxTextCtrl);
  m_staticText30 = XRCCTRL(*this,"m_staticText30",wxStaticText);
  m_textModelFile = XRCCTRL(*this,"m_textModelFile",wxTextCtrl);
  m_btModelOpen = XRCCTRL(*this,"m_btModelOpen",wxButton);
  m_btMatrixEdit = XRCCTRL(*this,"m_btMatrixEdit",wxButton);
  m_btMatrixSave = XRCCTRL(*this,"m_btMatrixSave",wxButton);
  m_btMatrixClear = XRCCTRL(*this,"m_btMatrixClear",wxButton);
  m_11 = XRCCTRL(*this,"m_11",wxStaticText);
  m_12 = XRCCTRL(*this,"m_12",wxStaticText);
  m_13 = XRCCTRL(*this,"m_13",wxStaticText);
  m_14 = XRCCTRL(*this,"m_14",wxStaticText);
  m_21 = XRCCTRL(*this,"m_21",wxStaticText);
  m_22 = XRCCTRL(*this,"m_22",wxStaticText);
  m_23 = XRCCTRL(*this,"m_23",wxStaticText);
  m_24 = XRCCTRL(*this,"m_24",wxStaticText);
  m_31 = XRCCTRL(*this,"m_31",wxStaticText);
  m_32 = XRCCTRL(*this,"m_32",wxStaticText);
  m_33 = XRCCTRL(*this,"m_33",wxStaticText);
  m_34 = XRCCTRL(*this,"m_34",wxStaticText);
  m_41 = XRCCTRL(*this,"m_41",wxStaticText);
  m_42 = XRCCTRL(*this,"m_42",wxStaticText);
  m_43 = XRCCTRL(*this,"m_43",wxStaticText);
  m_44 = XRCCTRL(*this,"m_44",wxStaticText);
  m_btEditMesh = XRCCTRL(*this,"m_btEditMesh",wxButton);
  m_spinEffect = XRCCTRL(*this,"m_spinEffect",wxSpinButton);
  m_btEffectAdd = XRCCTRL(*this,"m_btEffectAdd",wxButton);
  m_btEffectEdit = XRCCTRL(*this,"m_btEffectEdit",wxButton);
  m_btEffectCopy = XRCCTRL(*this,"m_btEffectCopy",wxButton);
  m_btEffectDel = XRCCTRL(*this,"m_btEffectDel",wxButton);
  m_btEffectAuto = XRCCTRL(*this,"m_btEffectAuto",wxButton);
  m_btEffectClear = XRCCTRL(*this,"m_btEffectClear",wxButton);
  m_btLoad = XRCCTRL(*this,"m_btLoad",wxButton);
  m_btOk = XRCCTRL(*this,"m_btOk",wxButton);
  m_btCancel = XRCCTRL(*this,"m_btCancel",wxButton);
 }
public:
dlgModel(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};

void 
InitXmlModel();
#endif
