//
// This file was automatically generated by wxrc, do not edit by hand.
//

#ifndef __xrc_texture_h__
#define __xrc_texture_h__
class dlgTexture : public wxDialog {
protected:
 wxStaticText* m_staticText5;
 wxTextCtrl* m_textTextureName;
 wxToggleButton* m_togglePreview;
 wxStaticLine* m_staticline11;
 wxStaticText* m_staticText9;
 wxCheckBox* m_checkCustom1;
 wxCheckBox* m_checkCustom2;
 wxCheckBox* m_checkCustom3;
 wxStaticLine* m_staticline1;
 wxStaticText* m_staticText6;
 wxTextCtrl* m_textFramerate;
 wxPanel* m_panelPreview;
 wxSpinButton* m_spinFrame;
 wxButton* m_btFrameAdd;
 wxButton* m_btFrameEdit;
 wxButton* m_btFrameCopy;
 wxButton* m_btFrameDel;
 wxButton* m_btFrameClear;
 wxSpinButton* m_spinAnimation;
 wxButton* m_btAnimationAdd;
 wxButton* m_btAnimationCopy;
 wxButton* m_btAnimationDel;
 wxToggleButton* m_toggleAnimationFreeze;
 wxButton* m_btAnimationClear;
 wxButton* m_btLoad;
 wxButton* m_btOk;
 wxButton* m_btCancel;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,_T("dlgTexture"), _T("wxDialog"));
  m_staticText5 = XRCCTRL(*this,"m_staticText5",wxStaticText);
  m_textTextureName = XRCCTRL(*this,"m_textTextureName",wxTextCtrl);
  m_togglePreview = XRCCTRL(*this,"m_togglePreview",wxToggleButton);
  m_staticline11 = XRCCTRL(*this,"m_staticline11",wxStaticLine);
  m_staticText9 = XRCCTRL(*this,"m_staticText9",wxStaticText);
  m_checkCustom1 = XRCCTRL(*this,"m_checkCustom1",wxCheckBox);
  m_checkCustom2 = XRCCTRL(*this,"m_checkCustom2",wxCheckBox);
  m_checkCustom3 = XRCCTRL(*this,"m_checkCustom3",wxCheckBox);
  m_staticline1 = XRCCTRL(*this,"m_staticline1",wxStaticLine);
  m_staticText6 = XRCCTRL(*this,"m_staticText6",wxStaticText);
  m_textFramerate = XRCCTRL(*this,"m_textFramerate",wxTextCtrl);
  m_panelPreview = XRCCTRL(*this,"m_panelPreview",wxPanel);
  m_spinFrame = XRCCTRL(*this,"m_spinFrame",wxSpinButton);
  m_btFrameAdd = XRCCTRL(*this,"m_btFrameAdd",wxButton);
  m_btFrameEdit = XRCCTRL(*this,"m_btFrameEdit",wxButton);
  m_btFrameCopy = XRCCTRL(*this,"m_btFrameCopy",wxButton);
  m_btFrameDel = XRCCTRL(*this,"m_btFrameDel",wxButton);
  m_btFrameClear = XRCCTRL(*this,"m_btFrameClear",wxButton);
  m_spinAnimation = XRCCTRL(*this,"m_spinAnimation",wxSpinButton);
  m_btAnimationAdd = XRCCTRL(*this,"m_btAnimationAdd",wxButton);
  m_btAnimationCopy = XRCCTRL(*this,"m_btAnimationCopy",wxButton);
  m_btAnimationDel = XRCCTRL(*this,"m_btAnimationDel",wxButton);
  m_toggleAnimationFreeze = XRCCTRL(*this,"m_toggleAnimationFreeze",wxToggleButton);
  m_btAnimationClear = XRCCTRL(*this,"m_btAnimationClear",wxButton);
  m_btLoad = XRCCTRL(*this,"m_btLoad",wxButton);
  m_btOk = XRCCTRL(*this,"m_btOk",wxButton);
  m_btCancel = XRCCTRL(*this,"m_btCancel",wxButton);
 }
public:
dlgTexture(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class dlgTextureFrame : public wxDialog {
protected:
 wxStaticText* m_staticText6;
 wxTextCtrl* m_textTextureFile;
 wxButton* m_btTextureInfo;
 wxButton* m_btTextureOpen;
 wxStaticText* m_staticText8;
 wxTextCtrl* m_textAlphaFile;
 wxButton* m_btAlphaInfo;
 wxButton* m_btAlphaOpen;
 wxButton* m_btLoad;
 wxButton* m_btOk;
 wxButton* m_btCancel;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,_T("dlgTextureFrame"), _T("wxDialog"));
  m_staticText6 = XRCCTRL(*this,"m_staticText6",wxStaticText);
  m_textTextureFile = XRCCTRL(*this,"m_textTextureFile",wxTextCtrl);
  m_btTextureInfo = XRCCTRL(*this,"m_btTextureInfo",wxButton);
  m_btTextureOpen = XRCCTRL(*this,"m_btTextureOpen",wxButton);
  m_staticText8 = XRCCTRL(*this,"m_staticText8",wxStaticText);
  m_textAlphaFile = XRCCTRL(*this,"m_textAlphaFile",wxTextCtrl);
  m_btAlphaInfo = XRCCTRL(*this,"m_btAlphaInfo",wxButton);
  m_btAlphaOpen = XRCCTRL(*this,"m_btAlphaOpen",wxButton);
  m_btLoad = XRCCTRL(*this,"m_btLoad",wxButton);
  m_btOk = XRCCTRL(*this,"m_btOk",wxButton);
  m_btCancel = XRCCTRL(*this,"m_btCancel",wxButton);
 }
public:
dlgTextureFrame(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};

void 
InitXmlTexture();
#endif
