//
// This file was automatically generated by wxrc, do not edit by hand.
//

#ifndef __xrc_texturesimple_h__
#define __xrc_texturesimple_h__
class dlgTextureSimple : public wxDialog {
protected:
 wxStaticText* m_staticText5;
 wxTextCtrl* m_textTextureName;
 wxStaticText* m_staticText6;
 wxTextCtrl* m_textTextureFile;
 wxButton* m_btTextureInfo;
 wxButton* m_btTextureOpen;
 wxStaticText* m_staticText8;
 wxTextCtrl* m_textAlphaFile;
 wxButton* m_btAlphaInfo;
 wxButton* m_btAlphaOpen;
 wxStaticText* m_staticText9;
 wxChoice* m_choiceColors;
 wxButton* m_btAdvanced;
 wxButton* m_btOk;
 wxButton* m_btCancel;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,_T("dlgTextureSimple"), _T("wxDialog"));
  m_staticText5 = XRCCTRL(*this,"m_staticText5",wxStaticText);
  m_textTextureName = XRCCTRL(*this,"m_textTextureName",wxTextCtrl);
  m_staticText6 = XRCCTRL(*this,"m_staticText6",wxStaticText);
  m_textTextureFile = XRCCTRL(*this,"m_textTextureFile",wxTextCtrl);
  m_btTextureInfo = XRCCTRL(*this,"m_btTextureInfo",wxButton);
  m_btTextureOpen = XRCCTRL(*this,"m_btTextureOpen",wxButton);
  m_staticText8 = XRCCTRL(*this,"m_staticText8",wxStaticText);
  m_textAlphaFile = XRCCTRL(*this,"m_textAlphaFile",wxTextCtrl);
  m_btAlphaInfo = XRCCTRL(*this,"m_btAlphaInfo",wxButton);
  m_btAlphaOpen = XRCCTRL(*this,"m_btAlphaOpen",wxButton);
  m_staticText9 = XRCCTRL(*this,"m_staticText9",wxStaticText);
  m_choiceColors = XRCCTRL(*this,"m_choiceColors",wxChoice);
  m_btAdvanced = XRCCTRL(*this,"m_btAdvanced",wxButton);
  m_btOk = XRCCTRL(*this,"m_btOk",wxButton);
  m_btCancel = XRCCTRL(*this,"m_btCancel",wxButton);
 }
public:
dlgTextureSimple(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};

void 
InitXmlTextureSimple();
#endif
