#ifndef CXMLNAMESPACECONSTANTS_H_INCLUDED
#define CXMLNAMESPACECONSTANTS_H_INCLUDED

#define NAMESPACE_RELAXNG "http://relaxng.org/ns/structure/1.0"

#endif // CXMLNAMESPACECONSTANTS_H_INCLUDED
