///////////////////////////////////////////////////////////////////////////////
//
// RCT3 Injector
// Copyright (C) 2008 Tobias Minch
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 3
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, <http://www.gnu.org/licenses/>.
//
// Written by
//   Tobias Minich - belgabor@gmx.de
//
///////////////////////////////////////////////////////////////////////////////


#ifndef __injector_main__
#define __injector_main__

/**
@file
Subclass of rcfrmMain, which is generated by wxFormBuilder.
*/

#include "resources\res_main.h"

/** Implementing rcfrmMain */
class frmMain : public rcfrmMain {
public:
	/** Constructor */
	frmMain( wxWindow* parent );
	
protected:
	virtual void OnExitClick( wxCommandEvent& event );
	virtual void OnInstallClick( wxCommandEvent& event ){ DoInstall(); }
	virtual void OnReexamineClick( wxCommandEvent& event ){ DoReexamine(); }
	virtual void OnUninstallClick( wxCommandEvent& event ){ DoUninstall(); }

private:
	bool m_installed;
	bool m_initialinstall;
	
	void DoInstall();
	void DoReexamine();
	void DoUninstall();
	
	void UpdateButtons();
};

#endif // __injector_main__
